import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, extname } from 'path';
import 'dotenv/config';

const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL!;
const MAPPING_FILE = join(process.cwd(), 'scripts', 'image-map.json');
const ROOT = process.cwd();

// Load the mapping generated by upload script
const mapping: Record<string, string> = JSON.parse(readFileSync(MAPPING_FILE, 'utf8'));

// Get all .tsx and .ts files recursively (excluding node_modules, .next, scripts)
function getSourceFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (['node_modules', '.next', 'scripts', '.git', '.claude'].includes(entry)) continue;
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      results.push(...getSourceFiles(fullPath));
    } else if (/\.(tsx?|mjs)$/.test(extname(fullPath))) {
      results.push(fullPath);
    }
  }
  return results;
}

// Sort mapping keys by length (longest first) to avoid partial replacements
const sortedKeys = Object.keys(mapping).sort((a, b) => b.length - a.length);

const files = getSourceFiles(ROOT);
console.log(`Scanning ${files.length} source files...`);

let totalReplacements = 0;
let filesModified = 0;

for (const filePath of files) {
  let content = readFileSync(filePath, 'utf8');
  let modified = false;

  for (const localPath of sortedKeys) {
    const r2Url = mapping[localPath];
    if (content.includes(localPath)) {
      content = content.split(localPath).join(r2Url);
      modified = true;
    }
  }

  if (modified) {
    // Count how many R2 URLs are in the file now vs before
    const beforeCount = (readFileSync(filePath, 'utf8').match(new RegExp(R2_PUBLIC_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length;
    const afterCount = (content.match(new RegExp(R2_PUBLIC_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length;
    totalReplacements += (afterCount - beforeCount);
    filesModified++;

    writeFileSync(filePath, content, 'utf8');
    const rel = filePath.replace(ROOT, '').replace(/^[\\/]/, '');
    console.log(`[${filesModified}] ${rel}`);
  }
}

console.log(`\nDone! Modified ${filesModified} files with ${totalReplacements} URL replacements.`);
